//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazingRaceApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvolvedTeam
    {
        public int EventID { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string DeviceID { get; set; }
        public Nullable<decimal> CurrentLatitude { get; set; }
        public Nullable<decimal> CurrentLongtitude { get; set; }
        public Nullable<int> NumOfClearned { get; set; }
        public Nullable<decimal> DistanceToNext { get; set; }
    }
}
